# Generated by Django 4.0.4 on 2022-05-11 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_lkcdatas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lkcdatas',
            old_name='image',
            new_name='imageLogo',
        ),
    ]
