# Generated by Django 4.0.4 on 2022-05-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_rename_image_lkcdatas_imagelogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageAboutUs', models.ImageField(blank=True, upload_to='aboutUs')),
                ('title', models.TextField(max_length=255)),
                ('desc', models.TextField(max_length=599)),
            ],
        ),
    ]
