# Generated by Django 4.0.4 on 2022-05-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='LKCActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageAboutUs', models.ImageField(blank=True, upload_to='aboutUs')),
            ],
        ),
    ]
